### 概述
+ 期约是对尚不存在的结果的一个替身。期约描述的都是一种异步程序执行机制
### 1、Promiss/A+规范
+ ECMAScript6增加了对Promiss规范的完整支持，即Promiss类型
### 2、期约基础
+ ECMAScript新增的引用类型Promise，可以通过new操作符来实例化。创建新期约时需要传入执行器（executor）函数作为参数
```js
	let p = new Promise(()=>{});
	setTimeout(console.log,0,p);
	//Promise {<pending>}
```
#### 2.1、期约状态机
+ 在把一个期约实例传给console.log()，控制台输出表明该实例处于待定(pending)状态。
+ 期约是一个有状态的对象，可能处于以下状态
	1. 待定（pending）
	2. 兑现（fulfilled，有时候称为解决，resolved）
	3. 拒绝（rejected）
+ **待定：** 是期约的最初是状态。在待定状态下，期约可以**落定**为代表成功的**兑现**状态或者代表失败的**拒绝**状态。不论落定为哪种状态都是不可逆的。
+ 期约的状态是私有的不可被检测到或者代码修改
#### 2.2、解决值、拒绝理由及期约用例
+ 期约的用途：首先是抽象地表示一个异步操作。期约的状态代表期约是否完成。“待定”表示尚未开始或者正在执行中。“兑现”表示以及成功完成，而“拒绝”表示则没有成功完成
+ 某些情况下，这个状态机就是期约可以提供的最有用的信息。知道一段异步代码已经完成，对于其他代码已经足够了。比如，假设期约要向服务器发送一个HTTP请求。请求返回200~299范围内的状态码就足以让期约的状态变为“兑现”。类似地，如果返回请求在200~299这个范围外则将期约的状态切换为“拒绝”
+ 在另外的一些情况下，期约封装的异步操作会实际生成某个值，而程序期待期约状态可以访问这个值。相应的，如果期约被拒绝，程序就会期待期约状态改变时可以拿到拒绝的理由。比如，假设期约向服务器发送一个HTTP请求并预定会返回JSON。如果请求返回范围在200~299状态码，则足以让期约转换为兑现。此时期约内部就可以受到一个JSON字符串，相反则收到ERROR兑现
+ 为了支持这两中用例，每个期约只要状态切换为兑现，就会有一个私有的内部值。类似的，每个期约只要状态切换为拒绝，就会有一个私有内部理由。不论是值还是理由，都是包含原始值或对象的不可修改的引用。二者是可逆的，默认为undefined。
#### 2.3、通过执行函数控制期约状态
+ 由于期约的状态是私有的，所以只能在内部进行操作。内部操作在期约的执行器函数中完成。执行器函数主要有两项职责：初始化期约的异步行为和控制状态的最终转换。
+ resolve( )：状态调为兑换
+ reject( )：状态调为拒绝
```js
	let p = new 
	Promise((resolve,reject)=>setTimeout(resolve,1000));
	setTimeout(console.log,0,p);
	//Promise {<pending>}
	// 不论resolve()和reject()中哪个被调用，状态转换都不可撤销了。
	// 于是修改状态会静默失败
	p = new Promise((resolve,reject)=>{
		resolve();
		reject();//修改失败
	});
	setTimeout(console.log,0,p);
	//Promise {<fulfilled>}
```
+ 为了避免期约卡在待定状态，可以添加一个定时退出功能，例如通过setTime函数设置多少秒后不论如何都会拒绝期约
```js
	let p = new Promise((resolve,reject)=>{
		setTimeout(reject,10000);
	});
	setTimeout(console.log,0,p);
	//Promise {<pending>}
	setTimeout(console.log,11000,p);//11秒后更新状态
	//Promise {<fulfilled>}
```
+ 如果执行器中的代码在超时之前已经解决或拒绝，那么超时回调会再次尝试拒绝也会失败
#### 2.4、Promise.resolve()
+ 期约并非一开始就必须处于待定状态的，然后通过执行器函数才能转换为落定状态。通过调用Promise.resolve( )的静态方法，可以实例化一个解决的期约。
```js
	let p1 = new Promise((resolve,reject)=>{resolve()});
	let p2 = Promise.resolve();
```
+ 这两个期约实例实际上是一样的
+ 这个解决期约值对应着的传给Promise.resolve( )的第一个参数。使用这个静态方法，实际上可以把任何值都转换为一个期约
```js
	setTimeout(console.log,0,Promise.resolve());
	//Promise {<fulfilled>: undefined}
	setTimeout(console.log,0,Promise.resolve(3));
	//Promise {<fulfilled>: 3}
	setTimeout(console.log,0,Promise.resolve(4,5));
	//Promise {<fulfilled>: 4}
```
+ 对于静态方法而言，如果传入参数本身就是一个期约，那么它的行为就类似于一个空包装。因此Promise.resolve()可以说是一个幂等方法
```js
	let p = new Promise(()=>{});
	setTimeout(console.log,0,p);
	//Promise {<pending>}
	setTimeout(console.log,0,Promise.resolve(p));
	//Promise {<pending>}
	setTimeout(console.log,0,p === Promise.resolve(p));
	//true
```
+ 这个幂等方法不论如何，执行过后结果仍然为传入的期约
+ 幂等方法，是指可以使用相同参数重复执行，并能获得相同结果的函数。这些**函数**不会影响系统状态，也不用担心重复执行会对系统造成改变。
+ 幂等性会保留传入期约的状态
+ **注意：** 这个静态方法能够包装任何非期约值，包括错误对象，并将其转换为解决的期约。因此可能导致不符合期约的行为
```js
	let p = Promise.resolve(new Error('foo'));
	setTimeout(console.log,0,p);
	//Promise {<fulfilled>: Error: foo
```
#### 2.5、Promise.reject( )
+ 与Promise.resolve( )类似，这个方法会实例化一个拒绝的期约并且抛出一个异步错误（无法通过try/catch捕获，而且能通过拒绝处理程序捕获）
+ 这个拒绝期约的理由就是传给Promise.reject( )的第一个参数。这个参数也会传给后续的拒绝处理程序：
```js
	let p = Promise.reject(3);
	setTimeout(console.log,0,p);
	//Promise {<rejected>: 3}
	p.then(null,(e)=>setTimeout(console.log,0,e));
	//3
```
+ 关键在于：Promise.reject( )并未照搬Promise.resolve( )的幂等逻辑。若传入一个期约对象则这个期约会成为它返回的拒绝期约的理由
```js
    setTimeout(console.log,0,
    Promise.reject(Promise.resolve(3)));
    //Promise {<rejected>: Promise}
```
#### 2.6、同步/异步执行的二元性
+ Promise的设计很大程度上会导致一种完全不同于js的计算模式。
```js
	try{
		throw new Error("foo");
	}catch(e){
		console.log(e);
	}
	//Error: foo
	try{
	   Promise.reject(new Error("bar"));
	}catch(e){
		console.log(e);
	}
	//Uncaught (in promise) Error: bar
```
+ 第一个try/catch抛出并捕获了任务，第二个try/catch抛出错误却并没有捕获到。乍一看这可能有一点违背直觉，因为代码确实同步创建了一个拒绝的期约实例，而这个实例也抛出了包含拒绝理由的错误。这里的同步代码之所以并没有捕获期约抛出的错误，是因为它没有通过异步模式捕获错误。而这里可以看出异步的特性：**它们是同步对象（在同步执行模式中使用），但也是异步执行模式的媒介**
+ 因此try/catch并不能捕获异步错误。代码一旦以异步模式开始执行，唯一与之交互的方式就是使用异步结构，具体的说就是使用期约的方法
### 3、期约的实例方法
+ 期约的实例方法是连接外部同步代码与内部异步代码之间的桥梁。这些方法可以访问异步操作返回的数据，处理期约成功和失败的结果，连续对期约求值，或者添加只有期约进入终止状态才会执行的代码
#### 3.1、实现Thenable接口
+ 在ECMAScript暴露的异步结构中，任何对象都有一个then()方法。这个方法被认为实现了Thenable接口
#### 3.2、Promise.prototype.then()
+ Promise.prototype.then( )是为期约实例添加处理程序的主要方法。这个then( )方法接收最多两个参数：onResolved处理程序与onRejected处理程序。这两个参数都是可选的，如果提供则会在期约分别进入“兑现”和“拒绝”状态时候自适应执行
```js
	function onResolved(id){
		setTimeout(console.log,0,id,"resolved");
	}
	function onRejected(id){
		setTimeout(console.log,0,id,"rejected");
	}
	let p1 = new Promise((resolve,reject)=> 
	setTimeout(resolve,3000));
	let p2 = new Promise((resolve,reject)=> 
	setTimeout(reject,3000));
	//3s后
	p1.then(()=>{onResolved("p1")},
			()=>{onRejected("p1")});
			//p1 rejected
	p2.then(()=>{onResolved("p2")},
			()=>{onRejected("p2")});
			//p2 rejected
```
+ 因为期约只能转换为最终的一次，所以两个操作一定是互斥的
+ 如上，两个处理程序参数都是可选的。而且。传给then( )的任何非函数类型的参数都会被静默忽略。如果只想提供onRejected参数，那就要在onResolved参数传入undefined就可。
+ **Promise.prototype.then( )** 方法会返回一个新的期约实例
```js
	console.log(p1.then(()=>{onResolved("p1")},
						()=>{onRejected("p1")}));
	//Promise {<pending>}
```
+ 这个新期约实例基于onResolved处理程序的返回值构建。换句话就是该处理程序的返回值会通过Promise.resolve( )包装过后生成的新期约。如果没有提供这个处理程序，则Promise.resolve()就会包装上一个期约解决后的值。如果没有显式的返回语句，则Promise.resolve( )会包装默认的返回值undefined
```js
	let p1 = Promise.resolve("Estella");
	let p2 = p1.then();
	let p3 = p1.then(()=>Promise.reject());
	let p4 = p1.then(()=>{});
	setTimeout(console.log,0,p2);
	//Promise {<fulfilled>: 'Estella'}
	setTimeout(console.log,0,p3);
	//Promise {<rejected>: undefined}
	setTimeout(console.log,0,p4);
	//Promise {<fulfilled>: undefined}
	let p5 = p1.then(()=>"bar");
	setTimeout(console.log,0,p5);
	//Promise {<fulfilled>: 'bar'}
	//抛出异常则会返回拒绝的期约
	let p6 = p1.then(()=>{throw "baz";});
	//Uncaught (in promise) baz
	let p7 = p1.then(()=>Error("qux"));
	setTimeout(console.log,0,p7);
	//Promise {<fulfilled>: Error: qux
	//返回错误值并不会触发上面的拒绝行为，而是封装
	//在一个解决的期约之中
```
+ onRejected处理程序也与之类似:onRejected处理程序返回值也被Promise.resolve( )包装。乍一看可能违背直觉，但仔细想想onRejected不就是捕获异步错误吗?因此，拒绝处理程序在捕获错误后，不抛出异常是符合期约的行为，应该返回一个解决期约
```js
	let p1 = Promise.reject("foo");
	let p2 = p1.then();
	setTimeout(console.log,0,p2);
	//Promise {<rejected>: 'foo'}
	//Uncaught (in promise) foo
	let p3 = p1.then(null,()=>undefined);
	let p4 = p1.then(null,()=>Promise.resolve());
	let p5 = p1.then(null,()=>Error("qux"));
	setTimeout(console.log,0,p3);
	//Promise {<fulfilled>: undefined}
	setTimeout(console.log,0,p4);
	//Promise {<fulfilled>: undefined}
	setTimeout(console.log,0,p5);    
	//Promise {<fulfilled>: Error: qux
```
#### 3.3、Promise.prototype.catch()
+ Promise.prototype.catch()用于给期约添加拒绝处理程序。这个方法只接收一个参数：onRejected处理程序。事实上，这个方法为一个语法糖，相当于调用Promise.prototy.then(null,onRejected);
```js
	let p = Promise.reject();
	let onRejected = function(e){
		setTimeout(console.log,0,e,'rejected');
	};
	p.catch(()=>{onRejected(3)});
	//3 'rejected'
```
+ Promise.prototype.catch()返回一个新的期约实例
```js
	let p = new Promise((resolve,reject)=>{reject("rejected")});
	let p2 = p.catch((e)=>{});
	let p3 = p.catch(()=>Promise.resolve("resolved"));
	setTimeout(console.log,0,p2);
	//Promise {<rejected>: 'rejected'}
	setTimeout(console.log,0,p3);
	//Promise {<fulfilled>: 'resolved'}
```
+ 在返回新期约实例方面，Promise.prototype.catch()的行为与Pomise.prototype.then()的onRejected处理器一样
+ 需要注意的是，在期约不为rejected的时候，catch()返回的期约实例不会执行传入的函数固定返回期约实例为pending状态
#### 3.4、Promise.prototype.finally()
+ Promise.prototype.finally()用于给期约添加onFinally处理程序，这个处理程序不论期约转换为解决还是拒绝状态都会执行
+ 但finally程序没办法知道期约的状态是决绝还是拒绝状态，所以这个方法主要用于添加清理代码
```js
	let p1 = Promise.reject("foo").catch(()=>{});
	let p2 = Promise.resolve("baz");
	let onFinally = function(e){
		setTimeout(console.log,0,e,'Finally');
	}
	p1.finally(()=>{onFinally('p1')});
	p2.finally(()=>{onFinally('p2')});
	//p2 Finally
	//p1 Finally
```
+ Promise.prototype.finally()方法返回一个新的期约实例
+ 这个新期约不同于then( )或catch方式返回的实例。因为onFinally被设计为一个与状态无关的方法，所以在大多数情况下它将表现为父期约的传递。对于已解决状态和被拒绝状态都是如此
```js
	let p1 = Promise.resolve("foo");
	let p2 = p1.finally(()=>{Error('qux')});
	let p3 = p1.finally(()=>Promise.resolve("baz"));
	setTimeout(console.log,0,p2);
	//Promise {<fulfilled>: 'foo'}
	setTimeout(console.log,0,p3);
	//Promise {<fulfilled>: 'foo'}
```
+ 如果返回的是一个待定的期约，或者onFinally处理程序抛出了错误（显式的抛出或返回了一个拒绝期约），则会返回相应的期约（待定或拒绝）
#### 3.5、非重入期约方法
+ 当期约进入落定状态的时候，与该状态的处理程序仅仅会被**排期**，而并非立即执行。跟在添加这个处理程序的代码之后的同步代码一定会在处理程序之前先执行。即使期约一开始就是与附加处理程序相关联的状态，执行顺序也是这样的。
```js
	let p = Promise.resolve();
	p.then(()=>console.log('onResolved handler'));
	console.log('then() returns');
	//then() returns
	//onResolved handler
```
+ 同步代码一定先于处理程序执行
+ 先添加处理程序后解决期约也是一样的。如果添加处理程序后，同步代码才改变期约状态，那么处理程序仍然会基于该状态变化表现出非重入性
```js
	let synchronousResolve;
	let p = new Promise((resolve)=>{
		synchronousResolve = function() {
			console.log("1: invokeing resovle()");
			resolve();
			console.log("2: resolve() returns");
		}
	});
	p.then(()=>{console.log("4: then() handler executes")});
	synchronousResolve();
	console.log("3: synchronousResolve() returns");
	//1: invokeing resovle()
	//2: resolve() returns
	//3: synchronousResolve() returns
	//4: then() handler executes
```
+ 在这个例子中，即使期约状态变化发生在添加处理程序之后，处理程序也会等待运行的消息队列让它出列才会执行
#### 3.6、邻近处理程序的执行顺序
+ 如果给期约添加了多个处理程序，当期约状态变化时，相关处理程序会按照添加它们的顺序依次执行
#### 3.7、传递解决值和拒绝理由
+ 到了落定状态后，期约会提供其解决值（如果兑现）或拒绝理由（如果拒绝）给相关状态的处理程序
+ 拿到返回值后，就可以进一步对这个值进行操作。比如那第一次的网络请求返回的JSON是发送第二次请求必须的数据，呢吗第一次请求返回的值就应该传给onResolved处理程序继续处理。当然失败的网络请求也会把HTTP状态码传给onRejected处理程序
+ 在执行函数中，解决的值和拒绝的理由是分别作为resolve()和reject()的第一个参数往后传的。然后，这些值又会传给它们各自的处理程序，作为onResolved或onRejected处理程序的唯一参数
```js
	let p1 = new Promise((resolve,reject)=>
	{resolve('foo')});
	p1.then((value)=>console.log(value));
	//foo
	let p2 = new Promise((resolve,reject)=>
	{resolve('bar')});
	p2.then((reason)=>console.log(reason));
	//bar
```
+ Promise.resolve()和Promise.reject()在被调用的时候会接受解决值和拒绝理由，同样的它们返回期约也会传递给onRejected和onResovled处理程序
#### 3.8、拒绝期约与拒绝错误处理
+ 拒绝期约类似于throw( )表达式，因为它们都代表一种程序状态，即需要中断或特殊处理。
```js
	let p1 = new Promise((resolve,reject)=> 
	reject(Error('foo')));
	let p2 = new Promise((resolve,reject)=> {
	throw Error('foo')});
	let p3 = Promise.resolve().then(()=>{
	throw Error('foo')});
	p1.catch(()=>{});
	p2.catch(()=>{});
	p3.catch(()=>{});
	setTimeout(console.log,0,p1);
	//Promise {<rejected>: Error: foo
	setTimeout(console.log,0,p2);
	//Promise {<rejected>: Error: foo
	setTimeout(console.log,0,p3);
	//Promise {<rejected>: Error: foo
```
+ 在期约抛出错误的时候，因为错误实际上是从消息队列中的异步抛出的，所以并不会阻止运行时继续执行同步指令
+ 如前面的Promis.reject()示例，异步错误只能通过异步的onRejected处理程序捕获：如，then()，catch() ... 方法等。
+ 但这不包括执行函数内部抛出的错误，所以在执行函数内部仍然使用tyr/catch捕获错误
### 4、期约连锁与期约合成
+ 多个期约组合在一起可以构成强大的逻辑块
#### 4.1、期约连锁
+ 期约逐个连接起来是一种非常有用的编程模式。因为每个期约的实例方法都会返回一个新的期约对象，而这个新的期约又有自己的实例方法，这样的连缀方法调用就可以构成所谓的“期约连锁”，比如：
```js
	let p = new Promise((resolve,reject)=>{
		console.log('frist');
		resolve();
	});
	p.then(()=>{
		console.log("second");
	}).then(()=>{
		console.log("third");
	}).then(()=>{
		console.log("fourth");
	});
	//frist
	//second
	//third
	//fourth
```
+ 这样实现了一连串的同步任务。正因为如此，这种方法执行的任务没有那么有用，毕竟使用了4个同步函数也可以做到
+ 若想真正的执行异步任务，可以改写，让每个执行器都返回一个期约实例。这样就可以让每个后续期约都等待之前的期约，也就是串行化异步任务
```js
	function delayedResolve(str){
		return new Promise((resolve,reject)=>{
			console.log(str);
			setTimeout(resolve,1000);
		});
	}
	delayedResolve('p1 executor')
		.then(()=>delayedResolve('p2 executor'))
		.then(()=>delayedResolve('p3 executor'))
		.then(()=>delayedResolve('p4 executor'));
	//p1 executor
	//p2 executor
	//p3 executor
	//p4 executor
```
+ 每个后续处理程序都会等待前一个期约的解决，然后实例化一个新期约并返回它。这种结构可以简洁的将异步任务串行化，解决之前依赖回调的难题，函数版本
```js
	function delayedResolve(str,callback = null){
		console.log(str);
		callback && callback();
	}
	delayedResolve("p1 executor",()=>{
		delayedResolve("p2 executor",()=>{
			delayedResolve("p3 executor",()=>{
				delayedResolve("p4 executor");
			})
		})
	});
	//p1 executor
	//p2 executor
	//p3 executor
	//p4 executor
```
#### 4.2、期约图
+ 期约可以看成二叉树
#### 4.3、Promise.all()和Promise.race()
+ Promise提供两个将多个期约实例合成一个期约的静态方法
1. <font>Promise.all( )：</font> 
+ Promise.all( )静态方法创建的期约会在一组期约全部解决之后再解决。这个静态方法接收一个可迭代的对象，返回一个新的期约：
```js
	let p1 = Promise.all([
		Promise.resolve(),
		Promise.resolve()
	]);
	setTimeout(console.log,0,p1);
	//Promise {<fulfilled>: Array(2)}
	let p2 = Promise.all([3,4]);
	setTimeout(console.log,0,p2);
	//Promise {<fulfilled>: Array(2)}
	let p3 = Promise.all([]);
	setTimeout(console.log,0,p3);
	//Promise {<fulfilled>: Array(0)}
	let p4 = Promise.all();//无效语法
	setTimeout(console.log,0,p4);
	//Uncaught (in promise) TypeError:
```
+ 合成的期约只会在每个包含的期约都解决之后才会解决：
```js
	let solve;
	let p = Promise.all([
		Promise.resolve(),
		new Promise((resolve,reject)=>{
			solve = function(){
				setTimeout(resolve,1000);
			}
		})
	]);
	setTimeout(console.log,0,p);
	//Promise {<pending>}
	solve();
	setTimeout(console.log,1000,p);
	//Promise {<fulfilled>: Array(2)}
```
+ 如果有一个包含期约待定，则合成的期约也会待定。如果有一个包含的期约拒绝，则合成的期约也会拒绝
+ 如果所有期约都成功解决，则合成期约的解决值就是所有包含期约解决值的数组，按照迭代器顺序
```js
	let solve;
	let p = Promise.all([
		Promise.resolve("3"),
		new Promise((resolve,reject)=>{
			solve = function(){
				setTimeout(resolve,1000,"4");
			}
		})
	]);
	setTimeout(console.log,0,p);
	//Promise {<pending>}
	solve();
	setTimeout(console.log,1000,p);
	//Promise {<fulfilled>: Array(2)}
	p.then((value)=>{
		console.log(value);
	});
	// ['3', '4']
```
+ 如果有期约拒绝，则第一个拒绝的期约会将自己的理由作为合成期约的拒绝理由。之后再拒绝的期约不会影响最终期约的拒绝理由。不过这并不会影响所有包含期约正常的拒绝操作。合成的期约会静默处理包含期约的拒绝操作
```js
	let p = Promise.all([
		Promise.reject("3"),
		Promise.reject("4")
	]);
	p.catch((reason)=>{
		setTimeout(console.log,100,reason);
		//3
	});
```
2. Promise.race()
+ Promise.race( )静态方法返回一个包装期约，是一组集合中最先解决或拒绝的期约镜像。这个方法接收一个可迭代对象，返回一个新期约
+ Promise.race( )不会对解决或拒绝的期约区分对待。不论是解决还是拒绝，只要是第一个落定的期约，Promise.rance( )就会包装器解决值或拒绝理由并返回新期约；
```js
	let p = Promise.race([
		Promise.reject(4),
		new Promise((resolve,reject)=>
		setTimeout(resolve,1000))
	]);
	p.catch((e)=>{});
	setTimeout(console.log,0,p);
	//Promise {<rejected>: 4}
```
+ 如果有一个期约拒绝，只要它是第一个落定的，就会成为拒绝合成期约的理由。之后再拒绝的期约不会影响最终期约的拒绝理由。
#### 4.4、串行期约合成
+ 期约的另外一个特性为，异步产生值传递给处理程序。基于后续期约使用之前的返回值来串联期约是期约的基本功能
```js
	function addTow(x){
		return x + 2;
	}
	function addThree(x){
		return x + 3;
	}
	function addFive(x){
		return x + 5;
	}
	function compare(...funs){
		return (x) => {
			return funs.reduce((promise, fn)=>{
				let temp = promise.then(fn);
				return temp;
			},Promise.resolve(x));
		}
	}
	let addTen = compare(addTow,addThree,addFive);
	addTen(8).then(console.log);
```
### 5、期约的扩展
#### 5.1、期约取消
+ 我们可以在现有的基础上提供一种临时性的封装，以实现期约取消的功能
```js
<button id = "start">Start</button>
<button id = "cancel">Cancel</button>
<script>
	class CancelToken{
		constructor(cancelFn){
			this.promise = new
			Promise((resolve,reject)=>{
				cancelFn(()=>{       				     
				setTimeout(console.log,0,"cancelled");
					resolve();
				})
			});
		}
	}
	const startButton =
	document.querySelector("#start");
	const cancelButton = 
	document.querySelector("#cancel");
	function cancellableDelayedResolve(delay){
		setTimeout(console.log,0,"start delay");
		return new Promise((resolve,reject)=>{
			const id = setTimeout((()=>{
				setTimeout(console.log,0,"delayed 
				resolve");
				resolve();
			}),delay);
			const cancelToken = new 
			CancelToken((cancelCallback)=>{	
			cancelButton.addEventListener
			("click",cancelCallback);
			});		   
			cancelToken.promise.then(
			()=>clearTimeout(id));
		});
	}
	startButton.addEventListener("click",()=>{
		cancellableDelayedResolve(1000);
	});
</script>
```
#### 5.2、期约进度通知
+ 执行中的期约可能会有不少的离散“阶段”
+ ECMAScript并不支持进度追踪，但可以通过扩展来实现