### 1、try/catch语句
+ 任何可能出错的代码都应该放到try块中，而处理错误的代码放到catch中
```js
	try {
		//可能出错的代码
	} catch (error) {
		//出错时的处理机制
	}
```
+ 如果try中有代码发生错误，代码会立即跳出执行，并跳到catch块中。catch接收一个错误对象，该对象的message属性中包含了错误信息
#### 1.1、finally语句
+ try/catch语句中可选的finally句子始终指向。如果try或catch块无法阻止finally块执行，包括return语句
#### 1.2、错误类型
+ 代码执行过程中会发生各种类型的错误。每种类型都会对应一个错误发生时抛出的错误对象，有以下8种类型：
	+ Error
	+ InternalError
	+ EvalError
	+ RangeError
	+ ReferenceError
	+ SyntaxError
	+ TypeError
	+ URIError
+ Error是基本类型，所有错误类型继承error，该类型浏览器很少抛出，该类型的主要作用是用于开发者抛出自定义错误
+ 